# Dependabot version update and security PRs
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(frontend)"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(rust)"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker)"
